services:

  db:
    image: postgres:16
    container_name: navashop-db
    restart: always
    env_file:
      - .env  
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    external: true
