version: '3.8'

services:
  frontend:
    build: .
    container_name: navashop-ui
    ports:
      - "3000:80" # 3000 é a porta do host, 80 é do nginx
    restart: always
    networks:
      - app_network

networks:
  app_network:
    external: true
