services:
  api:
    build: .
    container_name: navashop-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:
    external: true